BaseURL = "https://nanabanana.cc/"
languageCode = "en-us"
title = "Nana Banana"
theme = "nana"

relativeURLS = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true

googleAnalytics = "UA-114931239-3"

[params]
description = "Nana Banana Art"

[params.homepage_meta_tags]
meta_description = "Nana Banana Art"
meta_keywords = "nanabanana,art"
meta_og_title = "Nana Banana Art"
meta_og_type = "website"
meta_og_url = "hhttps://nanabanana.cc"
meta_og_image = ""
meta_og_description = "Nana Banana Art"
meta_twitter_card = "summary_large_image"
meta_twitter_site = ""
meta_twitter_creator = ""

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/bootstrap.bundle.min.js"
